name: DBT CI

on:
  push:
    branches:
      - main # Runs only when you push to main branch

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DBT dependencies
        run: |
          pip install dbt-core dbt-snowflake

      - name: Set up DBT profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Run DBT models
        run: |
          dbt deps
          dbt run
          dbt test
